name: Deploy to render.com

on:
     push:
   branches:[main]

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
              - name: checkout
uses: actions/checkout@v3

     - name: set up Python
uses: actions/setup-python@v3
with:
 python-version: 3.9

     - name: Install Dependencies
run: |
  python -m pip install --upgrade pip
  pip install -r requirements.txt

     - name: Deploy
if: github.ref == 'refs/heads/main'
run:
         curl - X POST \ -H "Authorization: Bearer ${{ secrets.RENDER_KEY_DEV }}"
      -H "Content-Type: application/json"\
      "${{ secrets.RENDER_DEPLOY }}"
